### ISSUE TITLE
fails to build on 10.13.2

### ISSUE THREAD

**Issue by LauraKirby** [codeaholics/node-rdb-tools#6]
Node modules need to be updated to take into account a bug fix in `node-gyp`.  Node module`lzf` depends on it. When looking into `lzf`, the readme url (https://github.com/Sonetica/node-lzf#readme) listed within `node_modules/lzf/package.json` lead to a 404. 

```
npm i rdb-tools

> int64-native@0.2.1 install /Users/laura/Desktop/redis-db-test/node_modules/int64-native
> node-gyp configure && node-gyp build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/Int64/src/main.o
In file included from ../src/main.cc:8:
../src/Int64.h:10:22: error: expected class name
class Int64 : public ObjectWrap {
```

**Comment by codeaholics** [comment]
Pull requests welcome! :-)
